// src/tools/containerized.ts
// Docker-based multi-replica tools: build a Docker image from the Ballerina fat
// JAR, generate a docker-compose.bi.yml that joins the kafka-local network, and
// start/stop/scale N replicas against the bundled Kafka broker.

import path from "path";
import fs from "fs";
import * as docker from "../utils/docker.js";
import * as log from "../utils/logger.js";
import { resolveBiProjectPath, resolveComposeDir, DEFAULTS } from "../config.js";
import { extractConfigurableDefault } from "../utils/log-patterns.js";

// ── Shared helpers ────────────────────────────────────────────────────────────

function assertBiProject(biPath: string): void {
  const toml = path.join(biPath, "Ballerina.toml");
  if (!fs.existsSync(toml)) {
    throw new Error(
      `No Ballerina.toml found at ${biPath}. ` +
      "Run setup_kafka_and_bi or generate_bi_kafka_sample to create a project first.",
    );
  }
}

function findJar(biPath: string): string {
  const binDir = path.join(biPath, "target", "bin");
  if (!fs.existsSync(binDir)) {
    throw new Error(
      `No target/bin directory found. Run validate_bi_project (or build_bi_docker_image) ` +
      `to compile the project first.`,
    );
  }
  const jars = fs.readdirSync(binDir).filter((f) => f.endsWith(".jar"));
  if (jars.length === 0) {
    throw new Error(
      `No JAR found in ${binDir}. Run validate_bi_project first.`,
    );
  }
  return jars[0]; // take the first (usually only one)
}

function resolveComposeFile(biPath: string, composeFile: string): string {
  return path.isAbsolute(composeFile)
    ? composeFile
    : path.join(biPath, composeFile);
}

function readBalSources(biPath: string): string[] {
  try {
    return fs
      .readdirSync(biPath)
      .filter((f) => f.endsWith(".bal"))
      .map((f) => fs.readFileSync(path.join(biPath, f), "utf8"));
  } catch {
    return [];
  }
}

// ── Tool 6: build_bi_docker_image ─────────────────────────────────────────────

interface BuildBiDockerImageArgs {
  projectPath?: string;
  imageName?:   string;
  tag?:         string;
}

export async function buildBiDockerImage(args: BuildBiDockerImageArgs): Promise<string> {
  const lines: string[] = [log.header("Build BI Docker Image")];
  const biPath    = resolveBiProjectPath(args.projectPath);
  const imageName = args.imageName ?? "bi-kafka-demo";
  const tag       = args.tag       ?? "latest";
  const fullImage = `${imageName}:${tag}`;

  try { assertBiProject(biPath); } catch (e: any) {
    lines.push(log.err(e.message)); return lines.join("\n");
  }

  lines.push(log.info(`Project path : ${biPath}`));
  lines.push(log.info(`Image name   : ${fullImage}`));
  lines.push("");

  // Step 1: build the Ballerina fat JAR
  lines.push(log.run("Step 1/3 — Building Ballerina project (bal build)…"));
  lines.push(log.info("This may take up to 2 minutes on first run."));
  const buildResult = await docker.run("bal", ["build"], biPath, 180_000);
  if (!buildResult.ok) {
    lines.push(log.err("Ballerina build failed."));
    lines.push(buildResult.stderr || buildResult.stdout);
    return lines.join("\n");
  }
  lines.push(log.ok("Ballerina build succeeded."));
  lines.push("");

  // Step 2: generate the Dockerfile
  lines.push(log.run("Step 2/3 — Generating Dockerfile…"));
  let jarName: string;
  try { jarName = findJar(biPath); } catch (e: any) {
    lines.push(log.err(e.message)); return lines.join("\n");
  }

  const dockerfileContent = [
    "# Generated by kafka-bi-mcp-server — do not edit manually.",
    "# Base image: eclipse-temurin:21-jre",
    "# Ballerina Swan Lake (2201.x) compiles to Java 21 class files.",
    "# eclipse-temurin:21-jre is multi-arch (amd64 + arm64) — works on Apple Silicon.",
    "FROM eclipse-temurin:21-jre",
    "WORKDIR /app",
    `COPY target/bin/${jarName} app.jar`,
    'ENTRYPOINT ["java", "-jar", "app.jar"]',
  ].join("\n");

  const dockerfilePath = path.join(biPath, "Dockerfile");
  fs.writeFileSync(dockerfilePath, dockerfileContent, "utf8");
  lines.push(log.ok(`Dockerfile written: ${dockerfilePath}`));
  lines.push("");

  // Step 3: docker build
  lines.push(log.run(`Step 3/3 — Building Docker image ${fullImage}…`));
  const dockerBuild = await docker.run(
    "docker",
    ["build", "-t", fullImage, "-f", "Dockerfile", "."],
    biPath,
    120_000,
  );
  if (!dockerBuild.ok) {
    lines.push(log.err("docker build failed."));
    lines.push(dockerBuild.stderr || dockerBuild.stdout);
    return lines.join("\n");
  }
  lines.push(log.ok(`Image ${fullImage} built successfully.`));
  lines.push("");

  // Report image size
  const sizeResult = await docker.run(
    "docker",
    ["images", imageName, "--format", "{{.Repository}}:{{.Tag}}  {{.Size}}"],
    undefined,
    10_000,
  );
  if (sizeResult.ok && sizeResult.stdout.trim()) {
    lines.push(log.info(`Image size: ${sizeResult.stdout.trim()}`));
  }

  lines.push("");
  lines.push(log.info("Next steps:"));
  lines.push("  1. generate_bi_docker_compose  — create docker-compose.bi.yml");
  lines.push("  2. start_bi_replicas_containerized { replicas: 2 }  — start N containers");

  return lines.join("\n");
}

// ── Tool 7: generate_bi_docker_compose ───────────────────────────────────────

interface GenerateBiDockerComposeArgs {
  projectPath?:       string;
  imageName?:         string;
  tag?:               string;
  groupId?:           string;
  inputTopic?:        string;
  outputTopic?:       string;
  outputComposeFile?: string;
}

export async function generateBiDockerCompose(args: GenerateBiDockerComposeArgs): Promise<string> {
  const lines: string[] = [log.header("Generate BI Docker Compose File")];
  const biPath          = resolveBiProjectPath(args.projectPath);
  const imageName       = args.imageName       ?? "bi-kafka-demo";
  const tag             = args.tag             ?? "latest";
  const composeFileName = args.outputComposeFile ?? "docker-compose.bi.yml";
  const fullImage       = `${imageName}:${tag}`;

  try { assertBiProject(biPath); } catch (e: any) {
    lines.push(log.err(e.message)); return lines.join("\n");
  }

  // Read defaults from config.bal
  const sources   = readBalSources(biPath);
  const groupId   = args.groupId    ?? extractConfigurableDefault(sources, "kafkaGroupId")    ?? "order-processor";
  const input     = args.inputTopic ?? extractConfigurableDefault(sources, "kafkaTopic")      ?? "bi.orders.in";
  const output    = args.outputTopic?? extractConfigurableDefault(sources, "outputTopic")     ?? "bi.orders.out";

  lines.push(log.info(`Project path : ${biPath}`));
  lines.push(log.info(`Image        : ${fullImage}`));
  lines.push(log.info(`Consumer group: ${groupId}`));
  lines.push(log.info(`Input topic  : ${input}`));
  lines.push(log.info(`Output topic : ${output}`));
  lines.push(log.info(`Bootstrap    : ${DEFAULTS.KAFKA_BOOTSTRAP_INTERNAL}  (internal Docker network)`));
  lines.push("");

  // Generate compose file content
  // Uses `docker compose up --scale bi-service=N` to set replica count at startup.
  // The BI service joins the external kafka-local network so it can reach kafka:9093.
  const composeContent = `# Generated by kafka-bi-mcp-server — do not edit manually.
#
# Start N replicas:
#   docker compose -f ${composeFileName} up -d --scale bi-service=N
#
# Stop:
#   docker compose -f ${composeFileName} down

services:
  bi-service:
    image: ${fullImage}
    command:
      - "--"
      - "-CkafkaBootstrapServers=${DEFAULTS.KAFKA_BOOTSTRAP_INTERNAL}"
      - "-CkafkaGroupId=${groupId}"
      - "-CkafkaTopic=${input}"
      - "-CoutputTopic=${output}"
    restart: unless-stopped
    networks:
      - kafka-local

networks:
  kafka-local:
    external: true
    # This is the network created by the bundled Kafka docker-compose.yml.
    # Kafka is reachable at kafka:9093 (INTERNAL listener).
    # The host-facing bootstrap (localhost:9092) is NOT available inside containers.
`;

  const composePath = path.join(biPath, composeFileName);
  fs.writeFileSync(composePath, composeContent, "utf8");

  lines.push(log.ok(`Compose file written: ${composePath}`));
  lines.push("");
  lines.push("Generated file preview:");
  lines.push("─".repeat(64));
  lines.push(composeContent.trim());
  lines.push("─".repeat(64));
  lines.push("");
  lines.push(log.info("Next step:"));
  lines.push(`  start_bi_replicas_containerized { replicas: 2 }`);
  lines.push("");
  lines.push(log.info("Or manually:"));
  lines.push(`  docker compose -f ${composePath} up -d --scale bi-service=2`);

  return lines.join("\n");
}

// ── Tool 8: start_bi_replicas_containerized ──────────────────────────────────

interface StartBiReplicasContainerizedArgs {
  projectPath?:      string;
  composeFile?:      string;
  replicas?:         number;
  kafkaComposePath?: string;
}

export async function startBiReplicasContainerized(args: StartBiReplicasContainerizedArgs): Promise<string> {
  const lines: string[] = [log.header("Start Containerized BI Replicas")];
  const biPath         = resolveBiProjectPath(args.projectPath);
  const composeFileName = args.composeFile ?? "docker-compose.bi.yml";
  const replicas       = Math.max(1, args.replicas ?? 2);
  const kafkaComposeDir = resolveComposeDir(args.kafkaComposePath);
  const absComposeFile  = resolveComposeFile(biPath, composeFileName);

  lines.push(log.info(`Project path : ${biPath}`));
  lines.push(log.info(`Compose file : ${absComposeFile}`));
  lines.push(log.info(`Replicas     : ${replicas}`));
  lines.push("");

  // Check compose file exists
  if (!fs.existsSync(absComposeFile)) {
    lines.push(log.err(`Compose file not found: ${absComposeFile}`));
    lines.push(log.info("Run generate_bi_docker_compose first to create it."));
    return lines.join("\n");
  }

  // Verify Kafka is running
  lines.push(log.run("Checking Kafka broker health…"));
  const kafkaPs = await docker.composePs(kafkaComposeDir);
  const kafkaUp = kafkaPs.stdout.includes("kafka") && kafkaPs.stdout.includes("running");
  if (!kafkaUp) {
    lines.push(log.err("Kafka broker does not appear to be running."));
    lines.push(log.info("Run start_kafka first."));
    return lines.join("\n");
  }
  lines.push(log.ok("Kafka broker is running."));
  lines.push("");

  // Start replicas
  lines.push(log.run(`Starting ${replicas} BI replica(s) via Docker Compose…`));
  const upResult = await docker.run(
    "docker",
    ["compose", "-f", absComposeFile, "up", "-d", "--scale", `bi-service=${replicas}`],
    biPath,
    120_000,
  );

  if (!upResult.ok) {
    lines.push(log.err("docker compose up failed."));
    lines.push(upResult.stderr || upResult.stdout);
    lines.push("");
    lines.push(log.info("Common causes:"));
    lines.push("  • Image not built — run build_bi_docker_image first");
    lines.push("  • kafka-local network missing — run start_kafka first");
    return lines.join("\n");
  }

  lines.push(log.ok(`${replicas} replica(s) started.`));
  lines.push("");

  // Give containers a moment to initialise, then show status
  await docker.sleep(3_000);

  const psResult = await docker.run(
    "docker",
    ["compose", "-f", absComposeFile, "ps", "--format", "json"],
    biPath,
    15_000,
  );

  if (psResult.ok && psResult.stdout.trim()) {
    lines.push("Container status:");
    lines.push("─".repeat(64));
    for (const jsonLine of psResult.stdout.trim().split("\n")) {
      try {
        const c = JSON.parse(jsonLine);
        lines.push(`  ${c.Name}  ${c.Status}`);
      } catch { /* skip malformed */ }
    }
    lines.push("─".repeat(64));
  }

  lines.push("");
  lines.push(log.info(`Bootstrap server used by containers: ${DEFAULTS.KAFKA_BOOTSTRAP_INTERNAL}`));
  lines.push(log.info("Network joined: kafka-local (external)"));
  lines.push("");
  lines.push(log.info("To scale up/down: scale_bi_replicas { replicas: N }"));
  lines.push(log.info("To stop all:      stop_bi_replicas_containerized"));
  lines.push(log.info("To inspect group: inspect_consumer_group { groupId: \"<id>\" }"));

  return lines.join("\n");
}

// ── Tool 9: stop_bi_replicas_containerized ───────────────────────────────────

interface StopBiReplicasContainerizedArgs {
  projectPath?:  string;
  composeFile?:  string;
}

export async function stopBiReplicasContainerized(args: StopBiReplicasContainerizedArgs): Promise<string> {
  const lines: string[] = [log.header("Stop Containerized BI Replicas")];
  const biPath          = resolveBiProjectPath(args.projectPath);
  const composeFileName = args.composeFile ?? "docker-compose.bi.yml";
  const absComposeFile  = resolveComposeFile(biPath, composeFileName);

  lines.push(log.info(`Compose file: ${absComposeFile}`));
  lines.push("");

  if (!fs.existsSync(absComposeFile)) {
    lines.push(log.err(`Compose file not found: ${absComposeFile}`));
    lines.push(log.info("Nothing to stop."));
    return lines.join("\n");
  }

  lines.push(log.run("Stopping BI containers…"));
  const downResult = await docker.run(
    "docker",
    ["compose", "-f", absComposeFile, "down", "--remove-orphans"],
    biPath,
    60_000,
  );

  if (!downResult.ok) {
    lines.push(log.err("docker compose down failed."));
    lines.push(downResult.stderr || downResult.stdout);
    return lines.join("\n");
  }

  lines.push(log.ok("All BI containers stopped and removed."));
  lines.push(log.info("The Kafka broker and its topics are unaffected."));

  return lines.join("\n");
}

// ── Tool 10: scale_bi_replicas ────────────────────────────────────────────────

interface ScaleBiReplicasArgs {
  replicas:          number;
  projectPath?:      string;
  composeFile?:      string;
  kafkaComposePath?: string;
}

export async function scaleBiReplicas(args: ScaleBiReplicasArgs): Promise<string> {
  const lines: string[] = [log.header("Scale BI Replicas")];
  const biPath          = resolveBiProjectPath(args.projectPath);
  const composeFileName = args.composeFile ?? "docker-compose.bi.yml";
  const replicas        = Math.max(0, args.replicas);
  const kafkaComposeDir = resolveComposeDir(args.kafkaComposePath);
  const absComposeFile  = resolveComposeFile(biPath, composeFileName);

  lines.push(log.info(`Target replicas: ${replicas}`));
  lines.push(log.info(`Compose file   : ${absComposeFile}`));
  lines.push("");

  if (!fs.existsSync(absComposeFile)) {
    lines.push(log.err(`Compose file not found: ${absComposeFile}`));
    lines.push(log.info("Run generate_bi_docker_compose first."));
    return lines.join("\n");
  }

  if (replicas === 0) {
    lines.push(log.info("Scaling to 0 — stopping all BI containers."));
  }

  lines.push(log.run(`Scaling bi-service to ${replicas} replica(s)…`));
  const scaleResult = await docker.run(
    "docker",
    ["compose", "-f", absComposeFile, "up", "-d", "--scale", `bi-service=${replicas}`],
    biPath,
    60_000,
  );

  if (!scaleResult.ok) {
    lines.push(log.err("Scaling failed."));
    lines.push(scaleResult.stderr || scaleResult.stdout);
    return lines.join("\n");
  }

  lines.push(log.ok(`Scaled to ${replicas} replica(s).`));
  lines.push("");

  // Show updated container list
  await docker.sleep(2_000);
  const psResult = await docker.run(
    "docker",
    ["compose", "-f", absComposeFile, "ps", "--format", "json"],
    biPath,
    15_000,
  );

  if (psResult.ok && psResult.stdout.trim()) {
    const containers: string[] = [];
    for (const jsonLine of psResult.stdout.trim().split("\n")) {
      try {
        const c = JSON.parse(jsonLine);
        containers.push(`  ${c.Name}  ${c.Status}`);
      } catch { /* skip */ }
    }
    if (containers.length > 0) {
      lines.push("Running containers:");
      lines.push("─".repeat(56));
      for (const c of containers) lines.push(c);
      lines.push("─".repeat(56));
      lines.push("");
    } else if (replicas === 0) {
      lines.push(log.info("All BI containers have been removed."));
    }
  }

  // Show consumer group rebalance if Kafka is available
  if (replicas > 0) {
    const kafkaContainer = await docker.resolveContainerName(kafkaComposeDir, "kafka");
    if (kafkaContainer) {
      // Read groupId from the compose file to auto-detect it
      let groupId = "order-processor";
      try {
        const composeText = fs.readFileSync(absComposeFile, "utf8");
        const m = composeText.match(/-CkafkaGroupId=([^\s"]+)/);
        if (m) groupId = m[1];
      } catch { /* use default */ }

      lines.push(log.info(`Consumer group partition assignment (group: ${groupId}):`));
      lines.push(log.info("Kafka rebalances partitions across active consumers automatically."));
      lines.push(log.info("Use inspect_consumer_group to see the full partition assignment."));
    }
  }

  return lines.join("\n");
}
